#!/usr/bin/env bash

# Format all staged .nix files
staged_nix_files=$(git diff --cached --name-only --diff-filter=ACM | grep '\.nix$')

if [ -n "$staged_nix_files" ]; then
  echo "Formatting .nix files..."
  nix fmt

  # Re-add formatted files
  echo "$staged_nix_files" | xargs git add

  echo "Done."
fi
